# Generated by Django 4.2.8 on 2023-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer0', '0002_zinaf_moshtary_kode_meli_alter_moshtary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jens', models.CharField(max_length=16)),
                ('vazn', models.DecimalField(decimal_places=3, max_digits=3)),
                ('metraj', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FactorForoosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=0, max_digits=9)),
                ('tarikhe_foroosh', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('kharidar', models.ManyToManyField(to='customer0.moshtary')),
                ('tage_ha', models.ManyToManyField(to='factor0.tage')),
            ],
        ),
    ]
