# Generated by Django 5.0 on 2024-01-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0001_initial'),
        ('customer0', '0001_initial'),
        ('factor0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tage',
            options={'ordering': ['-jens_parche', '-vazn', '-metraj'], 'verbose_name_plural': 'Tage_ha'},
        ),
        migrations.RemoveField(
            model_name='tage',
            name='jens_parche',
        ),
        migrations.AddField(
            model_name='tage',
            name='jens_parche',
            field=models.CharField(default='nil-bangal', max_length=16),
        ),
        migrations.AddField(
            model_name='tage',
            name='rangrazi',
            field=models.CharField(default='sooper_derakhshan', max_length=30),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(decimal_places=3, default=120, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Hesab_daryafti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagdi', models.IntegerField(blank=True, null=True)),
                ('tarikhe_daryaft', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('chek', models.ManyToManyField(blank=True, null=True, to='chek0.chek')),
            ],
        ),
        migrations.CreateModel(
            name='Foroosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geymat', models.DecimalField(decimal_places=3, default=240, max_digits=6, null=True)),
                ('shomare_factor', models.IntegerField(blank=True, null=True)),
                ('tarikhe_foroosh', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('kharidar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer0.moshtary')),
                ('tage', models.ManyToManyField(blank=True, to='factor0.tage')),
                ('hesab_daryafti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factor0.hesab_daryafti')),
            ],
            options={
                'verbose_name_plural': 'Factors',
                'ordering': ['-shomare_factor'],
            },
        ),
        migrations.DeleteModel(
            name='FactorForoosh',
        ),
    ]
