# Generated by Django 5.0 on 2024-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='roll',
            field=models.ManyToManyField(to='factor0.roll'),
        ),
    ]
