# Generated by Django 5.0 on 2024-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='roll',
        ),
        migrations.AddField(
            model_name='invoice',
            name='roll',
            field=models.ManyToManyField(null=True, to='factor0.roll'),
        ),
    ]
