# Generated by Django 5.0 on 2024-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroosh',
            name='shomare_factor',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
