# Generated by Django 4.2.8 on 2023-12-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0002_alter_tage_metraj_alter_tage_vazn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorforoosh',
            options={'ordering': ['-tarikhe_foroosh']},
        ),
        migrations.AlterModelOptions(
            name='tage',
            options={'ordering': ['-vazn']},
        ),
    ]
