# Generated by Django 5.0 on 2024-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0002_alter_invoice_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
