# Generated by Django 4.2.8 on 2023-12-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0003_alter_factorforoosh_options_alter_tage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
