# Generated by Django 5.0 on 2024-01-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0004_remove_invoice_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
