# Generated by Django 4.2.8 on 2023-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0004_alter_tage_metraj_alter_tage_vazn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorforoosh',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
