# Generated by Django 5.0 on 2024-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0005_invoice_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(default=240, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='meter',
            field=models.IntegerField(default=120, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
