# Generated by Django 4.2.8 on 2023-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0005_alter_factorforoosh_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorforoosh',
            name='fee',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
