# Generated by Django 5.0 on 2024-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0006_alter_invoice_amount_alter_roll_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
