# Generated by Django 4.2.8 on 2023-12-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0006_alter_factorforoosh_fee_alter_tage_metraj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tage',
            old_name='jens',
            new_name='jens_parche',
        ),
    ]
