# Generated by Django 4.2.8 on 2023-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0007_rename_jens_tage_jens_parche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorforoosh',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.IntegerField(),
        ),
    ]
