# Generated by Django 5.0 on 2024-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0007_alter_roll_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='remaining',
        ),
    ]
