# Generated by Django 4.2.8 on 2023-12-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0008_alter_factorforoosh_fee_alter_tage_metraj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorforoosh',
            name='fee',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.CharField(max_length=16),
        ),
    ]
