# Generated by Django 4.2.8 on 2023-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0011_alter_tage_metraj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.IntegerField(default='120'),
        ),
    ]
