# Generated by Django 4.2.8 on 2024-01-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0013_factorforoosh_jame_kol_alter_factorforoosh_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorforoosh',
            name='shomare_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
