# Generated by Django 4.2.8 on 2024-01-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer0', '0002_zinaf_moshtary_kode_meli_alter_moshtary_name'),
        ('factor0', '0015_alter_factorforoosh_options_alter_tage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorforoosh',
            name='kharidar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer0.moshtary'),
        ),
    ]
