# Generated by Django 4.2.8 on 2024-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0017_rename_factorforoosh_foroosh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.CharField(blank=True, default='120', max_length=10),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
