# Generated by Django 4.2.8 on 2024-01-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0018_alter_tage_metraj_alter_tage_vazn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroosh',
            name='Jame_kol',
        ),
    ]
