# Generated by Django 4.2.8 on 2024-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0020_foroosh_mablag_kol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroosh',
            name='Mablag_kol',
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.IntegerField(blank=True, default=120),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
