# Generated by Django 4.2.8 on 2024-01-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0021_remove_foroosh_mablag_kol_alter_tage_metraj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tage',
            name='geymat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.FloatField(blank=True, default=120),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
