# Generated by Django 5.0 on 2024-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0022_alter_tage_geymat_alter_tage_metraj_alter_tage_vazn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tage',
            name='geymat',
            field=models.DecimalField(blank=True, decimal_places=2, default=240, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(blank=True, decimal_places=2, default=120, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
