# Generated by Django 5.0 on 2024-01-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0023_alter_tage_geymat_alter_tage_metraj_alter_tage_vazn'),
    ]

    operations = [
        migrations.AddField(
            model_name='foroosh',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=240, max_digits=6, null=True),
        ),
    ]
