# Generated by Django 5.0 on 2024-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0024_foroosh_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroosh',
            name='tage',
            field=models.ManyToManyField(blank=True, to='factor0.tage'),
        ),
    ]
