# Generated by Django 5.0 on 2024-01-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer0', '0004_alter_moshtary_options_alter_zinaf_options'),
        ('factor0', '0025_alter_foroosh_tage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foroosh',
            options={'ordering': ['-shomare_factor'], 'verbose_name_plural': 'Factors'},
        ),
        migrations.AlterModelOptions(
            name='tage',
            options={'ordering': ['-jens_parche', '-vazn', '-metraj'], 'verbose_name_plural': 'Tage_ha'},
        ),
        migrations.RemoveField(
            model_name='foroosh',
            name='total',
        ),
        migrations.AlterField(
            model_name='foroosh',
            name='kharidar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer0.moshtary'),
        ),
        migrations.AlterField(
            model_name='tage',
            name='geymat',
            field=models.DecimalField(decimal_places=2, default=240, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=6, null=True),
        ),
    ]
