# Generated by Django 5.0 on 2024-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0026_alter_foroosh_options_alter_tage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tage',
            name='geymat',
        ),
        migrations.AddField(
            model_name='foroosh',
            name='geymat',
            field=models.DecimalField(decimal_places=2, default=240, max_digits=6, null=True),
        ),
    ]
