# Generated by Django 5.0 on 2024-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0027_remove_tage_geymat_foroosh_geymat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroosh',
            name='geymat',
            field=models.DecimalField(decimal_places=3, default=240, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='metraj',
            field=models.DecimalField(decimal_places=3, default=120, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tage',
            name='vazn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
