# Generated by Django 5.0 on 2024-01-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0028_alter_foroosh_geymat_alter_tage_metraj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foroosh',
            name='baste_shod',
            field=models.CharField(choices=[('hagigi', 'hagigi'), ('hogogi', 'hogogi')], max_length=16, null=True),
        ),
    ]
