# Generated by Django 5.0 on 2024-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0003_alter_chek_options'),
        ('factor0', '0030_hesab_daryafti_foroosh_hesab_daryafti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesab_daryafti',
            name='chek',
        ),
        migrations.AddField(
            model_name='hesab_daryafti',
            name='chek',
            field=models.ManyToManyField(null=True, to='chek0.chek'),
        ),
    ]
