# Generated by Django 5.0 on 2024-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0031_remove_hesab_daryafti_chek_hesab_daryafti_chek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesab_daryafti',
            name='nagdi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
