# Generated by Django 5.0 on 2024-01-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0033_remove_hesab_daryafti_daftari_hesab_daryafti_daftari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesab_daryafti',
            name='nagdi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
