# Generated by Django 5.0 on 2024-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0034_alter_hesab_daryafti_nagdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroosh',
            name='baste_shod',
            field=models.CharField(choices=[('baste', 'baste'), ('baz', 'baz')], max_length=16, null=True),
        ),
    ]
