# Generated by Django 5.0 on 2024-01-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0035_alter_foroosh_baste_shod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroosh',
            name='Hesab_daryafti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factor0.hesab_daryafti'),
        ),
    ]
