# Generated by Django 5.0 on 2024-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0003_alter_chek_options'),
        ('factor0', '0036_alter_foroosh_hesab_daryafti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroosh',
            name='baste_shod',
        ),
        migrations.AlterField(
            model_name='hesab_daryafti',
            name='chek',
            field=models.ManyToManyField(blank=True, null=True, to='chek0.chek'),
        ),
    ]
