# Generated by Django 5.0 on 2024-01-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0037_remove_foroosh_baste_shod_alter_hesab_daryafti_chek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesab_daryafti',
            name='daftari',
        ),
    ]
