# Generated by Django 5.0 on 2024-01-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0038_remove_hesab_daryafti_daftari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foroosh',
            old_name='Hesab_daryafti',
            new_name='hesab_daryafti',
        ),
    ]
