# Generated by Django 5.0 on 2024-01-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor0', '0002_alter_tage_options_remove_tage_jens_tage_jens_parche_and_more'),
        ('factor0', '0039_rename_hesab_daryafti_foroosh_hesab_daryafti'),
    ]

    operations = [
    ]
