# Generated by Django 5.0 on 2024-01-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('national_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('phonr_number', models.CharField(max_length=16, unique=True)),
                ('address', models.TextField()),
                ('creditـlimit', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('real_or_lega_nationality', models.CharField(choices=[('hagigi', 'Hagigi'), ('hogogi', 'Hogogi')], max_length=16)),
                ('national_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Recipients',
                'ordering': ['-name'],
            },
        ),
    ]
