# Generated by Django 5.0 on 2024-01-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moshtary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kode_meli', models.CharField(blank=True, max_length=16, null=True)),
                ('shomare', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('sagfe_etebar', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Moshtari_ha',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZiNaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hagigi_or_hogogi', models.CharField(choices=[('hagigi', 'hagigi'), ('hogogi', 'hogogi')], max_length=16)),
                ('kode_meli', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Zinaf_ha',
                'ordering': ['-name'],
            },
        ),
    ]
