# Generated by Django 4.2.8 on 2023-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiNaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hagigi_or_hogogi', models.CharField(choices=[('hagigi', 'hagigi'), ('hogogi', 'hogogi')], max_length=16)),
                ('kode_meli', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='moshtary',
            name='kode_meli',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='moshtary',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
