# Generated by Django 5.0 on 2024-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zinaf',
            name='hagigi_or_hogogi',
            field=models.CharField(choices=[('hagigi', 'Hagigi'), ('hogogi', 'Hogogi')], max_length=16),
        ),
    ]
