# Generated by Django 5.0 on 2024-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer0', '0002_zinaf_moshtary_kode_meli_alter_moshtary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moshtary',
            options={'ordering': ['name']},
        ),
    ]
