# Generated by Django 5.0 on 2024-01-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_book', models.IntegerField(unique=True)),
                ('sayad', models.CharField(max_length=16, unique=True)),
                ('amount', models.CharField(max_length=20)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('dueـdate', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('holder', models.CharField(blank=True, max_length=100, null=True)),
                ('is_registered', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=16)),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='chekha')),
                ('chec_bearer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer0.client')),
            ],
            options={
                'ordering': ['-check_book'],
            },
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('chek', models.ManyToManyField(blank=True, to='chek0.czech')),
            ],
        ),
    ]
