# Generated by Django 5.0 on 2024-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='czech',
            name='is_registered',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=16, null=True),
        ),
    ]
