# Generated by Django 5.0 on 2024-01-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='czech',
            old_name='national_code',
            new_name='chek_owner_national_code',
        ),
    ]
