# Generated by Django 5.0 on 2024-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chek',
            name='ax',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
