# Generated by Django 4.2.8 on 2023-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chek',
            name='girande',
        ),
        migrations.RemoveField(
            model_name='chek',
            name='zi_naf',
        ),
        migrations.AddField(
            model_name='chek',
            name='ki_daryaft_kard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chek',
            name='magsad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
