# Generated by Django 5.0 on 2024-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0002_czech_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czech',
            name='is_registered',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
