# Generated by Django 5.0 on 2024-01-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chek0', '0002_remove_chek_girande_remove_chek_zi_naf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chek',
            options={'ordering': ['-daftar']},
        ),
    ]
